# Generated by Django 3.2.9 on 2021-11-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('trailer', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('tahun_rilis', models.DateTimeField()),
            ],
        ),
    ]
