# Generated by Django 3.2.9 on 2021-12-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfilm',
            name='poster',
            field=models.ImageField(upload_to=''),
        ),
    ]
