# Generated by Django 3.2.9 on 2021-12-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_sfilm_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfilm',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sfilm',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
