# Generated by Django 3.2.9 on 2021-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211205_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfilm',
            name='tahun_rilis',
            field=models.IntegerField(),
        ),
    ]
